# Generated by Django 5.0.7 on 2024-08-01 03:38

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Accounting_button', '0002_performersrates'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='StaffingSchedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField()),
                ('time_norm', models.PositiveIntegerField()),
                ('time_fund', models.PositiveIntegerField(editable=False)),
                ('wage_fund', models.DecimalField(decimal_places=2, editable=False, max_digits=15)),
                ('name', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='Accounting_button.functions_of_performers', unique=True)),
                ('owner', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='staffing_schedules', to=settings.AUTH_USER_MODEL)),
                ('rate', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='Accounting_button.performersrates')),
            ],
        ),
    ]
