# Generated by Django 5.0.7 on 2024-08-05 04:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Accounting_button', '0004_functions_of_organizers'),
    ]

    operations = [
        migrations.AlterField(
            model_name='staffingschedule',
            name='name',
            field=models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, to='Accounting_button.functions_of_performers'),
        ),
    ]
