# Generated by Django 5.0.7 on 2024-08-05 06:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Accounting_button', '0006_organizersrates'),
    ]

    operations = [
        migrations.AlterField(
            model_name='organizersrates',
            name='name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='Accounting_button.functions_of_organizers'),
        ),
    ]
