# Generated by Django 5.0.7 on 2024-08-06 06:24

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Accounting_button', '0009_groupsoftypesofwork'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TypesOfJobs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('time_standard', models.PositiveIntegerField()),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='types_of_jobs', to='Accounting_button.groupsoftypesofwork')),
                ('owner', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='types_of_jobs_owners', to=settings.AUTH_USER_MODEL)),
                ('tariff', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='tariffs', to='Accounting_button.performersrates')),
                ('tariff_name', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='tariff_names', to='Accounting_button.performersrates')),
            ],
        ),
    ]
