# Generated by Django 5.0.7 on 2024-08-06 06:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Accounting_button', '0010_typesofjobs'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='typesofjobs',
            name='tariff',
        ),
    ]
