# Generated by Django 5.0.7 on 2024-08-07 02:14

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Accounting_button', '0011_remove_typesofjobs_tariff'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Clients',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('short_title', models.CharField(max_length=255)),
                ('full_name', models.TextField()),
                ('contract_price', models.PositiveIntegerField()),
                ('inn', models.CharField(max_length=12)),
                ('contract_number_and_date', models.CharField(max_length=255)),
                ('activities', models.TextField()),
                ('number_of_nomenclature_groups', models.PositiveIntegerField()),
                ('contact_person', models.CharField(max_length=255)),
                ('telephone', models.CharField(max_length=20)),
                ('email', models.EmailField(max_length=254)),
                ('mailing_address', models.TextField()),
                ('hide_in_search', models.BooleanField(default=False)),
                ('comments', models.TextField(blank=True, null=True)),
                ('owner', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='clients', to=settings.AUTH_USER_MODEL)),
                ('tax_system', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='clients', to='Accounting_button.taxationsystems')),
            ],
        ),
    ]
