# Generated by Django 5.0.7 on 2024-08-07 07:08

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Accounting_button', '0012_clients'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='StandardOperationsLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time_standard', models.PositiveIntegerField()),
                ('rate', models.DecimalField(decimal_places=2, max_digits=10)),
                ('quantity', models.PositiveIntegerField()),
                ('all_the_time', models.PositiveIntegerField()),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='operations_logs', to='Accounting_button.clients')),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='operations_logs', to='Accounting_button.groupsoftypesofwork')),
                ('owner', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='operations_logs', to=settings.AUTH_USER_MODEL)),
                ('type_of_work', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='operations_logs', to='Accounting_button.typesofjobs')),
            ],
            options={
                'indexes': [models.Index(fields=['owner'], name='idx_owner'), models.Index(fields=['client'], name='idx_client'), models.Index(fields=['type_of_work'], name='idx_type_of_work')],
            },
        ),
    ]
