# Generated by Django 5.0.7 on 2024-08-08 04:14

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Accounting_button', '0014_remove_standardoperationslog_group_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='NonStandardOperationsLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content_of_the_work', models.TextField()),
                ('duration', models.PositiveIntegerField()),
                ('price', models.DecimalField(decimal_places=2, editable=False, max_digits=10)),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='non_standard_operations_logs', to='Accounting_button.clients')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='non_standard_operations_logs', to=settings.AUTH_USER_MODEL)),
                ('rate', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='non_standard_operations_logs', to='Accounting_button.performersrates')),
            ],
            options={
                'indexes': [models.Index(fields=['owner'], name='Accounting__owner_i_d79444_idx'), models.Index(fields=['client'], name='Accounting__client__fa86dc_idx')],
            },
        ),
    ]
