# Generated by Django 5.0.7 on 2024-08-09 02:07

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Accounting_button', '0017_typesofexpenses'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='IncomeJournal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.DecimalField(decimal_places=2, max_digits=10)),
                ('date_of_event', models.DateField()),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('comment', models.TextField(blank=True, null=True)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='income_journals', to='Accounting_button.clients')),
                ('name', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='income_journals', to='Accounting_button.typesofincome')),
                ('owner', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='income_journals', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'indexes': [models.Index(fields=['date_of_event'], name='Accounting__date_of_f69bd0_idx'), models.Index(fields=['client'], name='Accounting__client__71a9c3_idx')],
            },
        ),
    ]
