# Generated by Django 5.0.7 on 2024-08-09 04:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Accounting_button', '0018_incomejournal'),
    ]

    operations = [
        migrations.AlterField(
            model_name='incomejournal',
            name='client',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='income_journals', to='Accounting_button.clients'),
        ),
    ]
