# Generated by Django 5.0.7 on 2024-08-09 09:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Accounting_button', '0021_revenuebudget'),
    ]

    operations = [
        migrations.AlterField(
            model_name='revenuebudget',
            name='period',
            field=models.CharField(db_index=True, max_length=7),
        ),
    ]
